# Generated by Django 5.1 on 2024-08-17 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("WellenceApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="userEmail",
            new_name="Email",
        ),
    ]
