# Generated by Django 5.1 on 2024-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WellenceApp', '0002_rename_useremail_tasks_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
