# Generated by Django 5.1 on 2024-08-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WellenceApp", "0005_alter_tasks_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
