# Generated by Django 5.1.1 on 2024-10-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WellenceApp", "0008_alter_tasks_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
